version: 2 
dependencies:
  cache_directories:
    - ~/.cocoapods
jobs:
  build:
    macos:
      xcode: "10.0.0" 
    steps:
      - checkout 
      - run:
          name: Setup
          command: mkdir /tmp/archive && /tmp/out && cp options.plist /tmp/archive
      - run:
          name: Build Archive
          command: >
            xcodebuild -workspace SecureImage.xcworkspace
            -scheme SecureImage
            -configuration Release
            -archivePath /tmp/archive/SecureImage
            -xcconfig ci.xcconfig
            archive
      - run:
         name: Package
         command: pushd /tmp/archive && zip -r /tmp/out/SecureImage-${CIRCLE_BUILD_NUM}.zip .
      - store_artifacts:
          path: /tmp/out