version: 2 
dependencies:
  cache_directories:
    - ~/.cocoapods
jobs:
  build:
    macos:
      xcode: "10.0.0" 
    steps:
      - checkout 
      - run:
          name: Setup
          command: mkdir /tmp/out && cp options.plist /tmp/out
      - run:
          name: Build Archive
          command: xcodebuild -workspace SecureImage.xcworkspace -scheme SecureImage -configuration Release -xcconfig ci.xcconfig -archivePath /tmp/out/SecureImage archive
      - run:
         name: Package
         command: pushd /tmp/out && zip -r /tmp/SecureImage.zip .
      - store_artifacts:
          path: /tmp/SecureImage.zip