version: 2 
jobs:
  build:
    macos:
      xcode: "10.0.0" 
    steps:
      - checkout 
      - run:
          # build our application
          name: Build Application
          command: xcodebuild
      #- run:
      #    # compress Xcode's build output so that it can be stored as an artifact
      #    name: Compress app for storage
      #    command: zip -r app.zip build/Release/circleci-demo-macos.app
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: build
          destination: build

